let data = [{
    id: "117",
    avatar: "1693",
    name: "Áo giáp Vàng",
    type: "trangbi",
    sucmanh: "45000000",
    type2: "ao",
    class: "namek",
    mota: "Tăng thêm giáp",
    motadai: "Khi sử dụng sẽ tăng thêm giáp cho bản thân",
    khoa: "0",
    info: {
        hp: 0,
        giap: 720,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "nDpIAOldlt",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "116",
    avatar: "1693",
    name: "Áo giáp Đồng",
    type: "trangbi",
    sucmanh: "30000000",
    type2: "ao",
    class: "namek",
    mota: "Tăng thêm giáp",
    motadai: "Khi sử dụng sẽ tăng thêm giáp cho bản thân",
    khoa: "0",
    info: {
        hp: 0,
        giap: 600,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "nDpIAOldlt",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "115",
    avatar: "1692",
    name: "Áo sắt trơn",
    type: "trangbi",
    sucmanh: "13000000",
    type2: "ao",
    class: "namek",
    mota: "Tăng thêm giáp",
    motadai: "Khi sử dụng sẽ tăng thêm giáp cho bản thân",
    khoa: "0",
    info: {
        hp: 0,
        giap: 500,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "FpAneVLDpB",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "114",
    avatar: "1692",
    name: "Áo đồng trơn",
    type: "trangbi",
    sucmanh: "8700000",
    type2: "ao",
    class: "namek",
    mota: "Tăng thêm giáp",
    motadai: "Khi sử dụng sẽ tăng thêm giáp cho bản thân",
    khoa: "0",
    info: {
        hp: 0,
        giap: 350,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "FpAneVLDpB",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "113",
    avatar: "959",
    name: "Áo Choàng Kemi",
    type: "trangbi",
    sucmanh: "4500000",
    type2: "ao",
    class: "namek",
    mota: "Tăng thêm giáp",
    motadai: "Khi sử dụng sẽ tăng thêm giáp cho bản thân",
    khoa: "0",
    info: {
        hp: 0,
        giap: 250,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "xqrFSjJLpW",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "112",
    avatar: "959",
    name: "Áo choàng Picolo",
    type: "trangbi",
    sucmanh: "1000000",
    type2: "ao",
    class: "namek",
    mota: "Tăng thêm giáp",
    motadai: "Khi sử dụng sẽ tăng thêm giáp cho bản thân",
    khoa: "0",
    info: {
        hp: 0,
        giap: 140,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "xqrFSjJLpW",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "111",
    avatar: "942",
    name: "Áo picolo",
    type: "trangbi",
    sucmanh: "500000",
    type2: "ao",
    class: "namek",
    mota: "Tăng thêm giáp",
    motadai: "Khi sử dụng sẽ tăng thêm giáp cho bản thân",
    khoa: "0",
    info: {
        hp: 0,
        giap: 55,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "DtYIXLtZNa",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "110",
    avatar: "942",
    name: "Áo dende",
    type: "trangbi",
    sucmanh: "180000",
    type2: "ao",
    class: "namek",
    mota: "Tăng thêm giáp",
    motadai: "Khi sử dụng sẽ tăng thêm giáp cho bản thân",
    khoa: "0",
    info: {
        hp: 0,
        giap: 35,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "DtYIXLtZNa",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "109",
    avatar: "394",
    name: "Áo thun mềm",
    type: "trangbi",
    sucmanh: "50000",
    type2: "ao",
    class: "namek",
    mota: "Tăng thêm giáp",
    motadai: "Khi sử dụng sẽ tăng thêm giáp cho bản thân",
    khoa: "0",
    info: {
        hp: 0,
        giap: 20,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "BiZPigMSyQ",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "108",
    avatar: "394",
    name: "Áo thun cứng",
    type: "trangbi",
    sucmanh: "18000",
    type2: "ao",
    class: "namek",
    mota: "Tăng thêm giáp",
    motadai: "Khi sử dụng sẽ tăng thêm giáp cho bản thân",
    khoa: "0",
    info: {
        hp: 0,
        giap: 11,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "BiZPigMSyQ",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "107",
    avatar: "393",
    name: "Áo vải dày",
    type: "trangbi",
    sucmanh: "8000",
    type2: "ao",
    class: "namek",
    mota: "Tăng thêm giáp",
    motadai: "Khi sử dụng sẽ tăng thêm giáp cho bản thân",
    khoa: "0",
    info: {
        hp: 0,
        giap: 5,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "GWaMGFsEzy",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "106",
    avatar: "393",
    name: "Áo vản thun",
    type: "trangbi",
    sucmanh: "900",
    type2: "ao",
    class: "namek",
    mota: "Tăng thêm giáp",
    motadai: "Khi sử dụng sẽ tăng thêm giáp cho bản thân",
    khoa: "0",
    info: {
        hp: 0,
        giap: 3,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "GWaMGFsEzy",
        quan: "",
        dau: "",
        avatar: ""
    },
},

{
    id: "129",
    avatar: "1699",
    name: "Quần giáp vàng",
    type: "trangbi",
    sucmanh: "40000000",
    type2: "quan",
    class: "namek",
    mota: "Giúp tăng HP",
    motadai: "Khi sử dụng sẽ tăng HP và hồi HP.",
    khoa: "0",
    info: {
        hp: 50000,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 15000,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "QEXyeCEokM",
        dau: "",
        avatar: ""
    },
}, {
    id: "128",
    avatar: "1699",
    name: "Quần giáp đồng",
    type: "trangbi",
    sucmanh: "25000000",
    type2: "quan",
    class: "namek",
    mota: "Giúp tăng HP",
    motadai: "Khi sử dụng sẽ tăng HP và hồi HP.",
    khoa: "0",
    info: {
        hp: 45000,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 9000,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "QEXyeCEokM",
        dau: "",
        avatar: ""
    },
}, {
    id: "127",
    avatar: "1698",
    name: "Quần sắt trơn",
    type: "trangbi",
    sucmanh: "10000000",
    type2: "quan",
    class: "namek",
    mota: "Giúp tăng HP",
    motadai: "Khi sử dụng sẽ tăng HP và hồi HP.",
    khoa: "0",
    info: {
        hp: 30000,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 6000,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "XPmKVVcYaU",
        dau: "",
        avatar: ""
    },
}, {
    id: "126",
    avatar: "1698",
    name: "Quần đồng trơn",
    type: "trangbi",
    sucmanh: "5000000",
    type2: "quan",
    class: "namek",
    mota: "Giúp tăng HP",
    motadai: "Khi sử dụng sẽ tăng HP và hồi HP.",
    khoa: "0",
    info: {
        hp: 19000,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 4000,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "XPmKVVcYaU",
        dau: "",
        avatar: ""
    },
}, {
    id: "125",
    avatar: "960",
    name: "Quần thun Picolo",
    type: "trangbi",
    sucmanh: "3000000",
    type2: "quan",
    class: "namek",
    mota: "Giúp tăng HP",
    motadai: "Khi sử dụng sẽ tăng HP và hồi HP.",
    khoa: "0",
    info: {
        hp: 12000,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 2000,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "XVStUvLNbr",
        dau: "",
        avatar: ""
    },
}, {
    id: "124",
    avatar: "960",
    name: "Quần võ picolo",
    type: "trangbi",
    sucmanh: "900000",
    type2: "quan",
    class: "namek",
    mota: "Giúp tăng HP",
    motadai: "Khi sử dụng sẽ tăng HP và hồi HP.",
    khoa: "0",
    info: {
        hp: 4000,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 300,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "XVStUvLNbr",
        dau: "",
        avatar: ""
    },
}, {
    id: "123",
    avatar: "943",
    name: "Quần bó dày",
    type: "trangbi",
    sucmanh: "400000",
    type2: "quan",
    class: "namek",
    mota: "Giúp tăng HP",
    motadai: "Khi sử dụng sẽ tăng HP và hồi HP.",
    khoa: "0",
    info: {
        hp: 1100,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 120,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "HmPctnhQwC",
        dau: "",
        avatar: ""
    },
}, {
    id: "122",
    avatar: "943",
    name: "Quần bó đen",
    type: "trangbi",
    sucmanh: "150000",
    type2: "quan",
    class: "namek",
    mota: "Giúp tăng HP",
    motadai: "Khi sử dụng sẽ tăng HP và hồi HP.",
    khoa: "0",
    info: {
        hp: 700,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 50,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "HmPctnhQwC",
        dau: "",
        avatar: ""
    },
}, {
    id: "121",
    avatar: "397",
    name: "Quần thun dày",
    type: "trangbi",
    sucmanh: "40000",
    type2: "quan",
    class: "namek",
    mota: "Giúp tăng HP",
    motadai: "Khi sử dụng sẽ tăng HP và hồi HP.",
    khoa: "0",
    info: {
        hp: 400,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 30,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "edetJJtBbw",
        dau: "",
        avatar: ""
    },
}, {
    id: "120",
    avatar: "397",
    name: "Quần vải thun",
    type: "trangbi",
    sucmanh: "14000",
    type2: "quan",
    class: "namek",
    mota: "Giúp tăng HP",
    motadai: "Khi sử dụng sẽ tăng HP và hồi HP.",
    khoa: "0",
    info: {
        hp: 300,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 15,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "edetJJtBbw",
        dau: "",
        avatar: ""
    },
}, {
    id: "119",
    avatar: "398",
    name: "Quần vải dày",
    type: "trangbi",
    sucmanh: "5000",
    type2: "quan",
    class: "namek",
    mota: "Giúp tăng HP",
    motadai: "Khi sử dụng sẽ tăng HP và hồi HP.",
    khoa: "0",
    info: {
        hp: 110,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 10,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "SaSEWzfnsr",
        dau: "",
        avatar: ""
    },
}, {
    id: "118",
    avatar: "398",
    name: "Quần vải đen",
    type: "trangbi",
    sucmanh: "1100",
    type2: "quan",
    class: "namek",
    mota: "Giúp tăng HP",
    motadai: "Khi sử dụng sẽ tăng HP và hồi HP.",
    khoa: "0",
    info: {
        hp: 18,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 3,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "SaSEWzfnsr",
        dau: "",
        avatar: ""
    },
},

{
    id: "141",
    avatar: "1705",
    name: "Giày Trơn Vàng",
    type: "trangbi",
    sucmanh: "35000000",
    type2: "giay",
    class: "namek",
    mota: "Giúp tăng KI",
    motadai: "Khi sử dụng sẽ tăng KI cho bản thân và hồi KI",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 70000,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 12000,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "140",
    avatar: "1705",
    name: "Giày trơn Bạc",
    type: "trangbi",
    sucmanh: "23500000",
    type2: "giay",
    class: "namek",
    mota: "Giúp tăng KI",
    motadai: "Khi sử dụng sẽ tăng KI cho bản thân và hồi KI",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 59000,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 9000,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "139",
    avatar: "1704",
    name: "Giày giáp vàng",
    type: "trangbi",
    sucmanh: "10200000",
    type2: "giay",
    class: "namek",
    mota: "Giúp tăng KI",
    motadai: "Khi sử dụng sẽ tăng KI cho bản thân và hồi KI",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 45000,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 6000,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "138",
    avatar: "1704",
    name: "Giày giáp bạc",
    type: "trangbi",
    sucmanh: "4350000",
    type2: "giay",
    class: "namek",
    mota: "Giúp tăng KI",
    motadai: "Khi sử dụng sẽ tăng KI cho bản thân và hồi KI",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 30000,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 3000,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "137",
    avatar: "963",
    name: "Giày dende",
    type: "trangbi",
    sucmanh: "1000000",
    type2: "giay",
    class: "namek",
    mota: "Giúp tăng KI",
    motadai: "Khi sử dụng sẽ tăng KI cho bản thân và hồi KI",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 19000,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 1200,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "136",
    avatar: "963",
    name: "Giày picolo",
    type: "trangbi",
    sucmanh: "300000",
    type2: "giay",
    class: "namek",
    mota: "Giúp tăng KI",
    motadai: "Khi sử dụng sẽ tăng KI cho bản thân và hồi KI",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 5500,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 500,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "135",
    avatar: "945",
    name: "Giày vải mềm",
    type: "trangbi",
    sucmanh: "190000",
    type2: "giay",
    class: "namek",
    mota: "Giúp tăng KI",
    motadai: "Khi sử dụng sẽ tăng KI cho bản thân và hồi KI",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 4700,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 300,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "134",
    avatar: "945",
    name: "Giày vải cứng",
    type: "trangbi",
    sucmanh: "50000",
    type2: "giay",
    class: "namek",
    mota: "Giúp tăng KI",
    motadai: "Khi sử dụng sẽ tăng KI cho bản thân và hồi KI",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 1200,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 100,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "133",
    avatar: "406",
    name: "Giày vải thun",
    type: "trangbi",
    sucmanh: "25000",
    type2: "giay",
    class: "namek",
    mota: "Giúp tăng KI",
    motadai: "Khi sử dụng sẽ tăng KI cho bản thân và hồi KI",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 360,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 15,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "132",
    avatar: "406",
    name: "Giày vải dày",
    type: "trangbi",
    sucmanh: "7000",
    type2: "giay",
    class: "namek",
    mota: "Giúp tăng KI",
    motadai: "Khi sử dụng sẽ tăng KI cho bản thân và hồi KI",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 130,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 10,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "131",
    avatar: "405",
    name: "Giày thun",
    type: "trangbi",
    sucmanh: "2500",
    type2: "giay",
    class: "namek",
    mota: "Giúp tăng KI",
    motadai: "Khi sử dụng sẽ tăng KI cho bản thân và hồi KI",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 50,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 5,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "130",
    avatar: "405",
    name: "Giày vải",
    type: "trangbi",
    sucmanh: "500",
    type2: "giay",
    class: "namek",
    mota: "Giúp tăng KI",
    motadai: "Khi sử dụng sẽ tăng KI cho bản thân và hồi KI",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 25,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 3,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
},

{
    id: "153",
    avatar: "1711",
    name: "Găng trơn Vàng",
    type: "trangbi",
    sucmanh: "52000000",
    type2: "gang",
    class: "namek",
    mota: "Giúp tăng tấn công",
    motadai: "Giúp bản thân tăng tấn công, có thể kết liễu đối thủ nhanh hơn.",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 1050,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "152",
    avatar: "1711",
    name: "Găng trơn bạc",
    type: "trangbi",
    sucmanh: "42000000",
    type2: "gang",
    class: "namek",
    mota: "Giúp tăng tấn công",
    motadai: "Giúp bản thân tăng tấn công, có thể kết liễu đối thủ nhanh hơn.",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 950,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "151",
    avatar: "1710",
    name: "Găng võ Picolo",
    type: "trangbi",
    sucmanh: "15000000",
    type2: "gang",
    class: "namek",
    mota: "Giúp tăng tấn công",
    motadai: "Giúp bản thân tăng tấn công, có thể kết liễu đối thủ nhanh hơn.",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 750,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "150",
    avatar: "1710",
    name: "Găng võ kami",
    type: "trangbi",
    sucmanh: "8300000",
    type2: "gang",
    class: "namek",
    mota: "Giúp tăng tấn công",
    motadai: "Giúp bản thân tăng tấn công, có thể kết liễu đối thủ nhanh hơn.",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 550,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "149",
    avatar: "948",
    name: "Găng võ octiu",
    type: "trangbi",
    sucmanh: "600000",
    type2: "gang",
    class: "namek",
    mota: "Giúp tăng tấn công",
    motadai: "Giúp bản thân tăng tấn công, có thể kết liễu đối thủ nhanh hơn.",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 330,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "148",
    avatar: "948",
    name: "Găng võ picolo",
    type: "trangbi",
    sucmanh: "300000",
    type2: "gang",
    class: "namek",
    mota: "Giúp tăng tấn công",
    motadai: "Giúp bản thân tăng tấn công, có thể kết liễu đối thủ nhanh hơn.",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 150,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "147",
    avatar: "961",
    name: "Găng Võ dêde",
    type: "trangbi",
    sucmanh: "250000",
    type2: "gang",
    class: "namek",
    mota: "Giúp tăng tấn công",
    motadai: "Giúp bản thân tăng tấn công, có thể kết liễu đối thủ nhanh hơn.",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 70,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "146",
    avatar: "961",
    name: "Găng võ kami",
    type: "trangbi",
    sucmanh: "95000",
    type2: "gang",
    class: "namek",
    mota: "Giúp tăng tấn công",
    motadai: "Giúp bản thân tăng tấn công, có thể kết liễu đối thủ nhanh hơn.",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 35,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "145",
    avatar: "412",
    name: "Găng thun mềm",
    type: "trangbi",
    sucmanh: "45000",
    type2: "gang",
    class: "namek",
    mota: "Giúp tăng tấn công",
    motadai: "Giúp bản thân tăng tấn công, có thể kết liễu đối thủ nhanh hơn.",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 12,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "144",
    avatar: "412",
    name: "Găng thun mỏng",
    type: "trangbi",
    sucmanh: "9000",
    type2: "gang",
    class: "namek",
    mota: "Giúp tăng tấn công",
    motadai: "Giúp bản thân tăng tấn công, có thể kết liễu đối thủ nhanh hơn.",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 9,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "143",
    avatar: "411",
    name: "Găng vải thun",
    type: "trangbi",
    sucmanh: "2500",
    type2: "gang",
    class: "namek",
    mota: "Giúp tăng tấn công",
    motadai: "Giúp bản thân tăng tấn công, có thể kết liễu đối thủ nhanh hơn.",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 4,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "142",
    avatar: "411",
    name: "Găng vải thô",
    type: "trangbi",
    sucmanh: "1000",
    type2: "gang",
    class: "namek",
    mota: "Giúp tăng tấn công",
    motadai: "Giúp bản thân tăng tấn công, có thể kết liễu đối thủ nhanh hơn.",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 1,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
},

];

module.exports = data;
