let data = [{
    id: "45",
    avatar: "1713",
    name: "Rada cấp 9",
    type: "trangbi",
    sucmanh: "4400000",
    type2: "rada",
    class: "all",
    mota: "Giúp tăng chí mạng",
    motadai: "Trang bị giúp nhân vật tăng chí mạng. Khi chí mạng sẽ x2 sát thương.",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 9,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "44",
    avatar: "1712",
    name: "Rada cấp 8",
    type: "trangbi",
    sucmanh: "1900000",
    type2: "rada",
    class: "all",
    mota: "Giúp tăng chí mạng",
    motadai: "Trang bị giúp nhân vật tăng chí mạng. Khi chí mạng sẽ x2 sát thương.",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 8,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "43",
    avatar: "1023",
    name: "Rada cấp 7",
    type: "trangbi",
    sucmanh: "8500000",
    type2: "rada",
    class: "all",
    mota: "Giúp tăng chí mạng",
    motadai: "Trang bị giúp nhân vật tăng chí mạng. Khi chí mạng sẽ x2 sát thương.",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 7,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "42",
    avatar: "1022",
    name: "Rada cấp 6",
    type: "trangbi",
    sucmanh: "3200000",
    type2: "rada",
    class: "all",
    mota: "Giúp tăng chí mạng",
    motadai: "Trang bị giúp nhân vật tăng chí mạng. Khi chí mạng sẽ x2 sát thương.",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 6,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: 41,
    avatar: "1021",
    name: "Rada cấp 5",
    type: "trangbi",
    sucmanh: "650000",
    type2: "rada",
    class: "all",
    mota: "Giúp tăng chí mạng",
    motadai: "Trang bị giúp nhân vật tăng chí mạng. Khi chí mạng sẽ x2 sát thương.",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 5,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "40",
    avatar: "1020",
    name: "Rada cấp 4",
    type: "trangbi",
    sucmanh: "130000",
    type2: "rada",
    class: "all",
    mota: "Giúp tăng chí mạng",
    motadai: "Trang bị giúp nhân vật tăng chí mạng. Khi chí mạng sẽ x2 sát thương.",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 4,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "39",
    avatar: "1019",
    name: "Rada cấp 3",
    type: "trangbi",
    sucmanh: "50000",
    type2: "rada",
    class: "all",
    mota: "Giúp tăng chí mạng",
    motadai: "Trang bị giúp nhân vật tăng chí mạng. Khi chí mạng sẽ x2 sát thương.",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 3,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "38",
    avatar: "434",
    name: "Rada cấp 2",
    type: "trangbi",
    sucmanh: "20000",
    type2: "rada",
    class: "all",
    mota: "Giúp tăng chí mạng",
    motadai: "Trang bị giúp nhân vật tăng chí mạng. Khi chí mạng sẽ x2 sát thương.",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 2,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "37",
    avatar: "433",
    name: "Rada cấp 1",
    type: "trangbi",
    sucmanh: "1000",
    type2: "rada",
    class: "all",
    mota: "Giúp tăng chí mạng",
    motadai: "Trang bị giúp nhân vật tăng chí mạng. Khi chí mạng sẽ x2 sát thương.",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 1,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, ];

module.exports = data;
