let data = [{
    id: "69",
    avatar: "1697",
    name: "Quần võ Kaio",
    type: "trangbi",
    sucmanh: "60000000",
    type2: "quan",
    class: "saiyan",
    mota: "Giúp tăng HP",
    motadai: "Sử dụng sẽ tăng HP",
    khoa: "0",
    info: {
        hp: 75000,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 20000,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "sGgYuUNKpv",
        dau: "",
        avatar: ""
    },
}, {
    id: "68",
    avatar: "1697",
    name: "Quần Kaio",
    type: "trangbi",
    sucmanh: "40000000",
    type2: "quan",
    class: "saiyan",
    mota: "Giúp tăng HP",
    motadai: "Sử dụng sẽ tăng HP",
    khoa: "0",
    info: {
        hp: 58000,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 12000,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "sGgYuUNKpv",
        dau: "",
        avatar: ""
    },
}, {
    id: "67",
    avatar: "1696",
    name: "Quần lưỡng long II",
    type: "trangbi",
    sucmanh: "17000000",
    type2: "quan",
    class: "saiyan",
    mota: "Giúp tăng HP",
    motadai: "Sử dụng sẽ tăng HP",
    khoa: "0",
    info: {
        hp: 43000,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 12000,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "JUZqBpawup",
        dau: "",
        avatar: ""
    },
}, {
    id: "66",
    avatar: "1696",
    name: "Quần lưỡng long",
    type: "trangbi",
    sucmanh: "11000000",
    type2: "quan",
    class: "saiyan",
    mota: "Giúp tăng HP",
    motadai: "Sử dụng sẽ tăng HP",
    khoa: "0",
    info: {
        hp: 30000,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 4000,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "JUZqBpawup",
        dau: "",
        avatar: ""
    },
}, {
    id: "65",
    avatar: "955",
    name: "Quần siêu Saiyan",
    type: "trangbi",
    sucmanh: "6000000",
    type2: "quan",
    class: "saiyan",
    mota: "Giúp tăng HP",
    motadai: "Sử dụng sẽ tăng HP",
    khoa: "0",
    info: {
        hp: 18000,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 1300,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "LxHAVZAfWv",
        dau: "",
        avatar: ""
    },
}, {
    id: "64",
    avatar: "955",
    name: "Quần saiyan",
    type: "trangbi",
    sucmanh: "2000000",
    type2: "quan",
    class: "saiyan",
    mota: "Giúp tăng HP",
    motadai: "Sử dụng sẽ tăng HP",
    khoa: "0",
    info: {
        hp: 7000,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 500,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "LxHAVZAfWv",
        dau: "",
        avatar: ""
    },
}, {
    id: "63",
    avatar: "935",
    name: "Quần giáp vàng II",
    type: "trangbi",
    sucmanh: "600000",
    type2: "quan",
    class: "saiyan",
    mota: "Giúp tăng HP",
    motadai: "Sử dụng sẽ tăng HP",
    khoa: "0",
    info: {
        hp: 1400,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 120,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "NMneWFprBj",
        dau: "",
        avatar: ""
    },
}, {
    id: "62",
    avatar: "935",
    name: "Quần giáp vàng",
    type: "trangbi",
    sucmanh: "200000",
    type2: "quan",
    class: "saiyan",
    mota: "Giúp tăng HP",
    motadai: "Sử dụng sẽ tăng HP",
    khoa: "0",
    info: {
        hp: 850,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 120,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "NMneWFprBj",
        dau: "",
        avatar: ""
    },
}, {
    id: "61",
    avatar: "399",
    name: "Quần giáp bạc",
    type: "trangbi",
    sucmanh: "50000",
    type2: "quan",
    class: "saiyan",
    mota: "Giúp tăng HP",
    motadai: "Sử dụng sẽ tăng HP",
    khoa: "0",
    info: {
        hp: 470,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 50,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "pRdIubbnej",
        dau: "",
        avatar: ""
    },
}, {
    id: "60",
    avatar: "399",
    name: "Quần giáp đồng",
    type: "trangbi",
    sucmanh: "17000",
    type2: "quan",
    class: "saiyan",
    mota: "Giúp tăng HP",
    motadai: "Sử dụng sẽ tăng HP",
    khoa: "0",
    info: {
        hp: 350,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 30,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "pRdIubbnej",
        dau: "",
        avatar: ""
    },
}, {
    id: "59",
    avatar: "400",
    name: "Quần thun dày",
    type: "trangbi",
    sucmanh: "7000",
    type2: "quan",
    class: "saiyan",
    mota: "Giúp tăng HP",
    motadai: "Sử dụng sẽ tăng HP",
    khoa: "0",
    info: {
        hp: 130,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 10,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "twvYYRSWUt",
        dau: "",
        avatar: ""
    },
}, {
    id: "58",
    avatar: "400",
    name: "Quần thun",
    type: "trangbi",
    sucmanh: "1000",
    type2: "quan",
    class: "saiyan",
    mota: "Giúp tăng HP",
    motadai: "Sử dụng sẽ tăng HP",
    khoa: "0",
    info: {
        hp: 22,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 5,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "twvYYRSWUt",
        dau: "",
        avatar: ""
    },
},

{
    id: "81",
    avatar: "1691",
    name: "áo Thần kaio",
    type: "trangbi",
    sucmanh: "60000000",
    type2: "ao",
    class: "saiyan",
    mota: "Giúp tăng giáp",
    motadai: "Tăng thêm giáp, giúp giảm sát thương từ đối phương",
    khoa: "0",
    info: {
        hp: 0,
        giap: 600,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "HJoHaDNBAZ",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "80",
    avatar: "1691",
    name: "Áo kaio",
    type: "trangbi",
    sucmanh: "45000000",
    type2: "ao",
    class: "saiyan",
    mota: "Giúp tăng giáp",
    motadai: "Tăng thêm giáp, giúp giảm sát thương từ đối phương",
    khoa: "0",
    info: {
        hp: 0,
        giap: 500,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "HJoHaDNBAZ",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "79",
    avatar: "1690",
    name: "Áo lông đỏ II",
    type: "trangbi",
    sucmanh: "19000000",
    type2: "ao",
    class: "saiyan",
    mota: "Giúp tăng giáp",
    motadai: "Tăng thêm giáp, giúp giảm sát thương từ đối phương",
    khoa: "0",
    info: {
        hp: 0,
        giap: 410,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "xtnMAjJsGX",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "78",
    avatar: "1690",
    name: "Áo lông đỏ",
    type: "trangbi",
    sucmanh: "11200000",
    type2: "ao",
    class: "saiyan",
    mota: "Giúp tăng giáp",
    motadai: "Tăng thêm giáp, giúp giảm sát thương từ đối phương",
    khoa: "0",
    info: {
        hp: 0,
        giap: 290,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "xtnMAjJsGX",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "77",
    avatar: "954",
    name: "Áo siêu Sanyan",
    type: "trangbi",
    sucmanh: "5500000",
    type2: "ao",
    class: "saiyan",
    mota: "Giúp tăng giáp",
    motadai: "Tăng thêm giáp, giúp giảm sát thương từ đối phương",
    khoa: "0",
    info: {
        hp: 0,
        giap: 190,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "FdtLeapDak",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "76",
    avatar: "954",
    name: "Áo Saiyan",
    type: "trangbi",
    sucmanh: "1500000",
    type2: "ao",
    class: "saiyan",
    mota: "Giúp tăng giáp",
    motadai: "Tăng thêm giáp, giúp giảm sát thương từ đối phương",
    khoa: "0",
    info: {
        hp: 0,
        giap: 120,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "FdtLeapDak",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "75",
    avatar: "934",
    name: "Áo giáp Vegeta",
    type: "trangbi",
    sucmanh: "630000",
    type2: "ao",
    class: "saiyan",
    mota: "Giúp tăng giáp",
    motadai: "Tăng thêm giáp, giúp giảm sát thương từ đối phương",
    khoa: "0",
    info: {
        hp: 0,
        giap: 45,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "JWIUYrfSuW",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "74",
    avatar: "934",
    name: "Áo giáp Vàng",
    type: "trangbi",
    sucmanh: "250000",
    type2: "ao",
    class: "saiyan",
    mota: "Giúp tăng giáp",
    motadai: "Tăng thêm giáp, giúp giảm sát thương từ đối phương",
    khoa: "0",
    info: {
        hp: 0,
        giap: 27,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "JWIUYrfSuW",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "73",
    avatar: "391",
    name: "Áo giáp sắt",
    type: "trangbi",
    sucmanh: "63000",
    type2: "ao",
    class: "saiyan",
    mota: "Giúp tăng giáp",
    motadai: "Tăng thêm giáp, giúp giảm sát thương từ đối phương",
    khoa: "0",
    info: {
        hp: 0,
        giap: 15,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "DaRJUvdSov",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "72",
    avatar: "391",
    name: "Áo giáp bạc",
    type: "trangbi",
    sucmanh: "25000",
    type2: "ao",
    class: "saiyan",
    mota: "Giúp tăng giáp",
    motadai: "Tăng thêm giáp, giúp giảm sát thương từ đối phương",
    khoa: "0",
    info: {
        hp: 0,
        giap: 8,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "DaRJUvdSov",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "71",
    avatar: "392",
    name: "Áo vải thun",
    type: "trangbi",
    sucmanh: "12000",
    type2: "ao",
    class: "saiyan",
    mota: "Giúp tăng giáp",
    motadai: "Tăng thêm giáp, giúp giảm sát thương từ đối phương",
    khoa: "0",
    info: {
        hp: 0,
        giap: 3,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "jmTItjaORo",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: 70,
    avatar: "392",
    name: "Áo vải thô",
    type: "trangbi",
    sucmanh: "1100",
    type2: "ao",
    class: "saiyan",
    mota: "Giúp tăng giáp",
    motadai: "Tăng thêm giáp, giúp giảm sát thương từ đối phương",
    khoa: "0",
    info: {
        hp: 0,
        giap: 1,
        chimang: 0,
        sucdanh: 0,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "jmTItjaORo",
        quan: "",
        dau: "",
        avatar: ""
    },
},

{
    id: "93",
    avatar: "1703",
    name: "Giày Thần Kaio",
    type: "trangbi",
    sucmanh: "50000000",
    type2: "giay",
    class: "saiyan",
    mota: "Giúp tăng KI",
    motadai: "Tăng KI cho bản thân",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 55000,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 15000,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "92",
    avatar: "1703",
    name: "Giày Kaio",
    type: "trangbi",
    sucmanh: "30000000",
    type2: "giay",
    class: "saiyan",
    mota: "Giúp tăng KI",
    motadai: "Tăng KI cho bản thân",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 49000,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 10000,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "91",
    avatar: "1702",
    name: "Giày lưỡng long 2",
    type: "trangbi",
    sucmanh: "15000000",
    type2: "giay",
    class: "saiyan",
    mota: "Giúp tăng KI",
    motadai: "Tăng KI cho bản thân",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 35000,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 5000,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "90",
    avatar: "1702",
    name: "Giày lưỡng long",
    type: "trangbi",
    sucmanh: "8000000",
    type2: "giay",
    class: "saiyan",
    mota: "Giúp tăng KI",
    motadai: "Tăng KI cho bản thân",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 23000,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 3000,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "89",
    avatar: "957",
    name: "Giày siêu saiyan",
    type: "trangbi",
    sucmanh: "1500000",
    type2: "giay",
    class: "saiyan",
    mota: "Giúp tăng KI",
    motadai: "Tăng KI cho bản thân",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 13000,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 1000,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "88",
    avatar: "957",
    name: "Giày saiyan",
    type: "trangbi",
    sucmanh: "500000",
    type2: "giay",
    class: "saiyan",
    mota: "Giúp tăng KI",
    motadai: "Tăng KI cho bản thân",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 4000,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 300,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "87",
    avatar: "936",
    name: "giày giáp vàng",
    type: "trangbi",
    sucmanh: "250000",
    type2: "giay",
    class: "saiyan",
    mota: "Giúp tăng KI",
    motadai: "Tăng KI cho bản thân",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 3500,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 100,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "86",
    avatar: "936",
    name: "giày giáp đồng",
    type: "trangbi",
    sucmanh: "100000",
    type2: "giay",
    class: "saiyan",
    mota: "Giúp tăng KI",
    motadai: "Tăng KI cho bản thân",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 850,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 50,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "85",
    avatar: "404",
    name: "giày ống bạc",
    type: "trangbi",
    sucmanh: "35000",
    type2: "giay",
    class: "saiyan",
    mota: "Giúp tăng KI",
    motadai: "Tăng KI cho bản thân",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 300,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 30,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "84",
    avatar: "404",
    name: "giày ống đồng",
    type: "trangbi",
    sucmanh: "15000",
    type2: "giay",
    class: "saiyan",
    mota: "Giúp tăng KI",
    motadai: "Tăng KI cho bản thân",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 90,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 20,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "83",
    avatar: "403",
    name: "giày vải dày",
    type: "trangbi",
    sucmanh: "3500",
    type2: "giay",
    class: "saiyan",
    mota: "Giúp tăng KI",
    motadai: "Tăng KI cho bản thân",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 38,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 10,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "82",
    avatar: "403",
    name: "giày vải thô",
    type: "trangbi",
    sucmanh: "1100",
    type2: "giay",
    class: "saiyan",
    mota: "Giúp tăng KI",
    motadai: "Tăng KI cho bản thân",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 0,
        ki: 19,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 5,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
},

{
    id: "105",
    avatar: "1709",
    name: "Găng Thần Kaio",
    type: "trangbi",
    sucmanh: "70000000",
    type2: "gang",
    class: "saiyan",
    mota: "Tăng tấn công",
    motadai: "Tăng thêm tấn công cho nhân vật. Giúp kết liễu đối thủ nhanh ho",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 1400,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "104",
    avatar: "1709",
    name: "Găng Kaio",
    type: "trangbi",
    sucmanh: "39000000",
    type2: "gang",
    class: "saiyan",
    mota: "Tăng tấn công",
    motadai: "Tăng thêm tấn công cho nhân vật. Giúp kết liễu đối thủ nhanh ho",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 950,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "103",
    avatar: "1708",
    name: "Găng lưỡng long 2",
    type: "trangbi",
    sucmanh: "39000000",
    type2: "gang",
    class: "saiyan",
    mota: "Tăng tấn công",
    motadai: "Tăng thêm tấn công cho nhân vật. Giúp kết liễu đối thủ nhanh ho",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 850,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "102",
    avatar: "1708",
    name: "Găng lưỡng long",
    type: "trangbi",
    sucmanh: "25000000",
    type2: "gang",
    class: "saiyan",
    mota: "Tăng tấn công",
    motadai: "Tăng thêm tấn công cho nhân vật. Giúp kết liễu đối thủ nhanh ho",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 450,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "101",
    avatar: "956",
    name: "Găng siêu saiyan",
    type: "trangbi",
    sucmanh: "11100000",
    type2: "gang",
    class: "saiyan",
    mota: "Tăng tấn công",
    motadai: "Tăng thêm tấn công cho nhân vật. Giúp kết liễu đối thủ nhanh ho",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 350,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "100",
    avatar: "956",
    name: "Găng saiyan",
    type: "trangbi",
    sucmanh: "800000",
    type2: "gang",
    class: "saiyan",
    mota: "Tăng tấn công",
    motadai: "Tăng thêm tấn công cho nhân vật. Giúp kết liễu đối thủ nhanh ho",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 220,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "99",
    avatar: "946",
    name: "Găng giáp vàng",
    type: "trangbi",
    sucmanh: "380000",
    type2: "gang",
    class: "saiyan",
    mota: "Tăng tấn công",
    motadai: "Tăng thêm tấn công cho nhân vật. Giúp kết liễu đối thủ nhanh ho",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 90,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "98",
    avatar: "946",
    name: "Găng giáp sắt",
    type: "trangbi",
    sucmanh: "150000",
    type2: "gang",
    class: "saiyan",
    mota: "Tăng tấn công",
    motadai: "Tăng thêm tấn công cho nhân vật. Giúp kết liễu đối thủ nhanh ho",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 45,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "97",
    avatar: "410",
    name: "Găng thun đồng",
    type: "trangbi",
    sucmanh: "55000",
    type2: "gang",
    class: "saiyan",
    mota: "Tăng tấn công",
    motadai: "Tăng thêm tấn công cho nhân vật. Giúp kết liễu đối thủ nhanh ho",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 18,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "96",
    avatar: "410",
    name: "Găng vải đồng",
    type: "trangbi",
    sucmanh: "15000",
    type2: "gang",
    class: "saiyan",
    mota: "Tăng tấn công",
    motadai: "Tăng thêm tấn công cho nhân vật. Giúp kết liễu đối thủ nhanh ho",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 12,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "95",
    avatar: "409",
    name: "văn vải thun",
    type: "trangbi",
    sucmanh: "3500",
    type2: "gang",
    class: "saiyan",
    mota: "Tăng tấn công",
    motadai: "Tăng thêm tấn công cho nhân vật. Giúp kết liễu đối thủ nhanh ho",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 7,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
}, {
    id: "94",
    avatar: "409",
    name: "Găng vải thô",
    type: "trangbi",
    sucmanh: "1000",
    type2: "gang",
    class: "saiyan",
    mota: "Tăng tấn công",
    motadai: "Tăng thêm tấn công cho nhân vật. Giúp kết liễu đối thủ nhanh ho",
    khoa: "0",
    info: {
        hp: 0,
        giap: 0,
        chimang: 0,
        sucdanh: 3,
        ki: 0,
        hutmau: 0,
        hoimau: 0,
        hoiki30s: 0,
        hoihp30s: 0,
        hoiki: 0,
        hutki: 0,
        phandon: 0,
        hoichieu: 0,
        gocgiap: 0,
        gochp: 0,
        gocki: 0,
        gocsucdanh: 0,
    },
    script: {
        ao: "",
        quan: "",
        dau: "",
        avatar: ""
    },
},
];

module.exports = data;
